/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author My User
 */
public class RadioGUI extends javax.swing.JFrame {
    
    //Atributos
    private RadioMain RADIO;
    
    /**
     * Creates new form RadioGUI
     */
    public RadioGUI() {
        initComponents();
        RadioMain radio1 = new RadioMain();
        this.RADIO = radio1;
        jTextField1.setText("");
        jButton11.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        jButton6.setEnabled(false);
        jButton7.setEnabled(false);
        jButton9.setEnabled(false);
        jButton10.setEnabled(false);
        jToggleButton1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton8 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Panasonic Radio");
        setBackground(new java.awt.Color(102, 102, 102));
        setForeground(new java.awt.Color(102, 102, 102));
        setLocation(new java.awt.Point(300, 250));
        getContentPane().setLayout(null);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 51, 0));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Radio");
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 51, 0), 3, true));
        jTextField1.setCaretColor(new java.awt.Color(0, 0, 153));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(130, 50, 487, 72);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/onbut1.jpg"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 50, 48, 45);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(130, 130, 75, 23);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("2");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(210, 130, 71, 23);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("3");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(290, 130, 74, 23);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("4");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(370, 130, 75, 23);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setText("5");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(450, 130, 79, 23);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("6");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(530, 130, 79, 23);

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton9.setText(">");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(670, 110, 50, 45);

        jButton10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton10.setText("<");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(620, 110, 47, 45);

        jButton11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton11.setText("FM/AM");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11);
        jButton11.setBounds(20, 110, 97, 45);

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jToggleButton1.setText("SAVE");
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(620, 50, 100, 50);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setText("12");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(530, 160, 73, 23);

        jButton12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton12.setText("7");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(130, 160, 70, 23);

        jButton13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton13.setText("8");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13);
        jButton13.setBounds(210, 160, 73, 23);

        jButton14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton14.setText("9");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14);
        jButton14.setBounds(290, 160, 73, 23);

        jButton15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton15.setText("10");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15);
        jButton15.setBounds(370, 160, 73, 23);

        jButton16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton16.setText("11");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16);
        jButton16.setBounds(450, 160, 73, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondonaranja3.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 740, 200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jToggleButton1.isSelected()){
            if (RADIO.getFrequency().equals("FM")){
                RADIO.setButton1(Double.parseDouble(RADIO.getStation()));
            } else {
                RADIO.setButton1AM(Double.parseDouble(RADIO.getStation()));
            }
            jTextField1.setText("SAVED");
            jToggleButton1.setSelected(false);
        } else { 
            if (RADIO.getFrequency().equals("FM")){
                RADIO.setStation(Double.toString(RADIO.getButton1()));
                jTextField1.setText(Double.toString(RADIO.getButton1()));
            } else {
                RADIO.setStation(Double.toString(RADIO.getButton1AM()));
                jTextField1.setText(Double.toString(RADIO.getButton1AM()));
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (RADIO.isON()){
            RADIO.OFF();
            jTextField1.setText("");
            jButton11.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false);
            jButton9.setEnabled(false);
            jButton10.setEnabled(false);
            jToggleButton1.setEnabled(false);
        } else {
            RADIO.ON();
            jTextField1.setText("Panasonic Radio");
            jButton11.setEnabled(true);
            jButton2.setEnabled(true);
            jButton3.setEnabled(true);
            jButton4.setEnabled(true);
            jButton5.setEnabled(true);
            jButton6.setEnabled(true);
            jButton7.setEnabled(true);
            jButton9.setEnabled(true);
            jButton10.setEnabled(true);
            jToggleButton1.setEnabled(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        RADIO.Forward();
        jTextField1.setText(RADIO.getStation());
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        RADIO.Backward();
        jTextField1.setText(RADIO.getStation());
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        if (RADIO.getFrequency().equals("FM")){
            RADIO.changeFrequency("AM");
            RADIO.setStation("530");
            jTextField1.setText("530.0");
        } else {
            RADIO.changeFrequency("FM");
            RADIO.setStation("87.9");
            jTextField1.setText("87.9");
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (jToggleButton1.isSelected()){
            if (RADIO.getFrequency().equals("FM")){
                RADIO.setButton2(Double.parseDouble(RADIO.getStation()));
            } else {
                RADIO.setButton2AM(Double.parseDouble(RADIO.getStation()));
            }
            jTextField1.setText("SAVED");
            jToggleButton1.setSelected(false);
        } else { 
            if (RADIO.getFrequency().equals("FM")){
                RADIO.setStation(Double.toString(RADIO.getButton2()));
                jTextField1.setText(Double.toString(RADIO.getButton2()));
            } else {
                RADIO.setStation(Double.toString(RADIO.getButton2AM()));
                jTextField1.setText(Double.toString(RADIO.getButton2AM()));
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (jToggleButton1.isSelected()){
            if (RADIO.getFrequency().equals("FM")){
                RADIO.setButton3(Double.parseDouble(RADIO.getStation()));
            } else {
                RADIO.setButton3AM(Double.parseDouble(RADIO.getStation()));
            }
            jTextField1.setText("SAVED");
            jToggleButton1.setSelected(false);
        } else { 
            if (RADIO.getFrequency().equals("FM")){
                RADIO.setStation(Double.toString(RADIO.getButton3()));
                jTextField1.setText(Double.toString(RADIO.getButton3()));
            } else {
                RADIO.setStation(Double.toString(RADIO.getButton3AM()));
                jTextField1.setText(Double.toString(RADIO.getButton3AM()));
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (jToggleButton1.isSelected()){
            if (RADIO.getFrequency().equals("FM")){
                RADIO.setButton4(Double.parseDouble(RADIO.getStation()));
            } else {
                RADIO.setButton4AM(Double.parseDouble(RADIO.getStation()));
            }
            jTextField1.setText("SAVED");
            jToggleButton1.setSelected(false);
        } else { 
            if (RADIO.getFrequency().equals("FM")){
                RADIO.setStation(Double.toString(RADIO.getButton4()));
                jTextField1.setText(Double.toString(RADIO.getButton4()));
            } else {
                RADIO.setStation(Double.toString(RADIO.getButton4AM()));
                jTextField1.setText(Double.toString(RADIO.getButton4AM()));
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (jToggleButton1.isSelected()){
            if (RADIO.getFrequency().equals("FM")){
                RADIO.setButton5(Double.parseDouble(RADIO.getStation()));
            } else {
                RADIO.setButton5AM(Double.parseDouble(RADIO.getStation()));
            }
            jTextField1.setText("SAVED");
            jToggleButton1.setSelected(false);
        } else { 
            if (RADIO.getFrequency().equals("FM")){
                RADIO.setStation(Double.toString(RADIO.getButton5()));
                jTextField1.setText(Double.toString(RADIO.getButton5()));
            } else {
                RADIO.setStation(Double.toString(RADIO.getButton5AM()));
                jTextField1.setText(Double.toString(RADIO.getButton5AM()));
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (jToggleButton1.isSelected()){
            if (RADIO.getFrequency().equals("FM")){
                RADIO.setButton6(Double.parseDouble(RADIO.getStation()));
            } else {
                RADIO.setButton6AM(Double.parseDouble(RADIO.getStation()));
            }
            jTextField1.setText("SAVED");
            jToggleButton1.setSelected(false);
        } else { 
            if (RADIO.getFrequency().equals("FM")){
                RADIO.setStation(Double.toString(RADIO.getButton6()));
                jTextField1.setText(Double.toString(RADIO.getButton6()));
            } else {
                RADIO.setStation(Double.toString(RADIO.getButton6AM()));
                jTextField1.setText(Double.toString(RADIO.getButton6AM()));
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (jToggleButton1.isSelected()){
            if (RADIO.getFrequency().equals("FM")){
                RADIO.setButton12(Double.parseDouble(RADIO.getStation()));
            } else {
                RADIO.setButton12AM(Double.parseDouble(RADIO.getStation()));
            }
            jTextField1.setText("SAVED");
            jToggleButton1.setSelected(false);
        } else { 
            if (RADIO.getFrequency().equals("FM")){
                RADIO.setStation(Double.toString(RADIO.getButton12()));
                jTextField1.setText(Double.toString(RADIO.getButton12()));
            } else {
                RADIO.setStation(Double.toString(RADIO.getButton12AM()));
                jTextField1.setText(Double.toString(RADIO.getButton12AM()));
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        if (jToggleButton1.isSelected()){
            if (RADIO.getFrequency().equals("FM")){
                RADIO.setButton8(Double.parseDouble(RADIO.getStation()));
            } else {
                RADIO.setButton8AM(Double.parseDouble(RADIO.getStation()));
            }
            jTextField1.setText("SAVED");
            jToggleButton1.setSelected(false);
        } else { 
            if (RADIO.getFrequency().equals("FM")){
                RADIO.setStation(Double.toString(RADIO.getButton8()));
                jTextField1.setText(Double.toString(RADIO.getButton8()));
            } else {
                RADIO.setStation(Double.toString(RADIO.getButton8AM()));
                jTextField1.setText(Double.toString(RADIO.getButton8AM()));
            }
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        if (jToggleButton1.isSelected()){
            if (RADIO.getFrequency().equals("FM")){
                RADIO.setButton9(Double.parseDouble(RADIO.getStation()));
            } else {
                RADIO.setButton9AM(Double.parseDouble(RADIO.getStation()));
            }
            jTextField1.setText("SAVED");
            jToggleButton1.setSelected(false);
        } else { 
            if (RADIO.getFrequency().equals("FM")){
                RADIO.setStation(Double.toString(RADIO.getButton9()));
                jTextField1.setText(Double.toString(RADIO.getButton9()));
            } else {
                RADIO.setStation(Double.toString(RADIO.getButton9AM()));
                jTextField1.setText(Double.toString(RADIO.getButton9AM()));
            }
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        if (jToggleButton1.isSelected()){
            if (RADIO.getFrequency().equals("FM")){
                RADIO.setButton10(Double.parseDouble(RADIO.getStation()));
            } else {
                RADIO.setButton10AM(Double.parseDouble(RADIO.getStation()));
            }
            jTextField1.setText("SAVED");
            jToggleButton1.setSelected(false);
        } else { 
            if (RADIO.getFrequency().equals("FM")){
                RADIO.setStation(Double.toString(RADIO.getButton10()));
                jTextField1.setText(Double.toString(RADIO.getButton10()));
            } else {
                RADIO.setStation(Double.toString(RADIO.getButton10AM()));
                jTextField1.setText(Double.toString(RADIO.getButton10AM()));
            }
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        if (jToggleButton1.isSelected()){
            if (RADIO.getFrequency().equals("FM")){
                RADIO.setButton11(Double.parseDouble(RADIO.getStation()));
            } else {
                RADIO.setButton11AM(Double.parseDouble(RADIO.getStation()));
            }
            jTextField1.setText("SAVED");
            jToggleButton1.setSelected(false);
        } else { 
            if (RADIO.getFrequency().equals("FM")){
                RADIO.setStation(Double.toString(RADIO.getButton11()));
                jTextField1.setText(Double.toString(RADIO.getButton11()));
            } else {
                RADIO.setStation(Double.toString(RADIO.getButton11AM()));
                jTextField1.setText(Double.toString(RADIO.getButton11AM()));
            }
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        if (jToggleButton1.isSelected()){
            if (RADIO.getFrequency().equals("FM")){
                RADIO.setButton7(Double.parseDouble(RADIO.getStation()));
            } else {
                RADIO.setButton7AM(Double.parseDouble(RADIO.getStation()));
            }
            jTextField1.setText("SAVED");
            jToggleButton1.setSelected(false);
        } else { 
            if (RADIO.getFrequency().equals("FM")){
                RADIO.setStation(Double.toString(RADIO.getButton7()));
                jTextField1.setText(Double.toString(RADIO.getButton7()));
            } else {
                RADIO.setStation(Double.toString(RADIO.getButton7AM()));
                jTextField1.setText(Double.toString(RADIO.getButton7AM()));
            }
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RadioGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
